name: Check links

on:
  push:
    branches:
      - add-header
  schedule:
    - cron: '45 01 30 * *'

jobs:
  test_links_utils:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: setup environment
      id: setup
      run: python -m pip install -r tests/requirements.colab.2024.02.txt

    - name: list packages
      id: list_pakcages
      run: python -m pip list

    - name: check links
      id: links
      run: python -m pytest -n auto ./tests/test_check_links_in_ipynb.py
