name: Check links

on: 
  schedule:
    - cron: '45 01 30 * *'
  push:

jobs:
  test_links_utils:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: true
        cache-suffix: "uv"
        cache-dependency-glob: "tests/requirements.colab.2025.02.txt"

    - name: Create venv
      run: uv venv my_env
  
    - name: setup environment
      id: setup
      run: |
        source my_env/bin/activate
        uv pip install -r ./utils/requirements.txt

    - name: list packages
      id: list_pakcages
      run: |
        source my_env/bin/activate
        uv pip list

    - name: check links
      id: links
      run: |
        source my_env/bin/activate
        python -m pytest -n auto ./tests/test_check_links_in_ipynb.py
